#!/bin/sh

type gmake > /dev/null 2>/dev/null
if [ "$?" -eq 0 ]; then
  MAKE=gmake
else
  MAKE=make
fi

mkdir -p _build/lib
rsync -a src/libre2 src/Makefile src/*.cpp src/*.h _build/lib
cd _build/lib

exec $MAKE ocaml-version-selected-include-path=$(ocamlfind printconf stdlib)
