#!/bin/sh

type gmake > /dev/null 2>/dev/null
if [ "$?" -eq 0 ]; then
  MAKE=gmake
else
  MAKE=make
fi

mkdir -p _build/lib
rsync -a lib/libre2 lib/Makefile lib/*.cpp lib/*.h _build/lib
cd _build/lib

exec $MAKE ocaml-version-selected-include-path=$(ocamlfind printconf stdlib)
